-- Migration: Add wizard fields to Employee table
-- Run manually in Supabase SQL editor (Schema: public)

ALTER TABLE "Employee"
  ADD COLUMN IF NOT EXISTS "nationalId"             TEXT,
  ADD COLUMN IF NOT EXISTS "passportNumber"          TEXT,
  ADD COLUMN IF NOT EXISTS "ethnicity"               TEXT,
  ADD COLUMN IF NOT EXISTS "religion"                TEXT,
  ADD COLUMN IF NOT EXISTS "allowProfileUpdate"      BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "needsTimeClock"          BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS "probationEndDate"        TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "placementEffectiveDate"  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "jobType"                 TEXT,
  ADD COLUMN IF NOT EXISTS "jobDescription"          TEXT,
  ADD COLUMN IF NOT EXISTS "leaveWorkflowKey"        TEXT,
  ADD COLUMN IF NOT EXISTS "workdayKey"              TEXT,
  ADD COLUMN IF NOT EXISTS "holidayKey"              TEXT,
  ADD COLUMN IF NOT EXISTS "termEffectiveDate"       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "contractStartDate"       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "contractEndDate"         TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "salaryEffectiveDate"     TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "currency"                TEXT DEFAULT 'PHP',
  ADD COLUMN IF NOT EXISTS "nextSalaryReviewDate"    TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "payMethod"               TEXT,
  ADD COLUMN IF NOT EXISTS "blogUrl"                 TEXT,
  ADD COLUMN IF NOT EXISTS "officePhone"             TEXT,
  ADD COLUMN IF NOT EXISTS "housePhone"              TEXT,
  ADD COLUMN IF NOT EXISTS "postcode"                TEXT,
  ADD COLUMN IF NOT EXISTS "country"                 TEXT DEFAULT 'Philippines',
  ADD COLUMN IF NOT EXISTS "heightCm"                DECIMAL(5,1),
  ADD COLUMN IF NOT EXISTS "weightKg"                DECIMAL(5,1),
  ADD COLUMN IF NOT EXISTS "bloodType"               TEXT,
  ADD COLUMN IF NOT EXISTS "visionL"                 TEXT,
  ADD COLUMN IF NOT EXISTS "visionR"                 TEXT,
  ADD COLUMN IF NOT EXISTS "hearingL"                TEXT,
  ADD COLUMN IF NOT EXISTS "hearingR"                TEXT,
  ADD COLUMN IF NOT EXISTS "handL"                   TEXT,
  ADD COLUMN IF NOT EXISTS "handR"                   TEXT,
  ADD COLUMN IF NOT EXISTS "legL"                    TEXT,
  ADD COLUMN IF NOT EXISTS "legR"                    TEXT,
  ADD COLUMN IF NOT EXISTS "spouseFirstName"         TEXT,
  ADD COLUMN IF NOT EXISTS "spouseMiddleName"        TEXT,
  ADD COLUMN IF NOT EXISTS "spouseLastName"          TEXT,
  ADD COLUMN IF NOT EXISTS "spouseBirthDate"         TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "spouseNationality"       TEXT,
  ADD COLUMN IF NOT EXISTS "spouseNationalId"        TEXT,
  ADD COLUMN IF NOT EXISTS "spousePassport"          TEXT,
  ADD COLUMN IF NOT EXISTS "spouseEthnicity"         TEXT,
  ADD COLUMN IF NOT EXISTS "spouseReligion"          TEXT,
  ADD COLUMN IF NOT EXISTS "spouseWorking"           BOOLEAN,
  ADD COLUMN IF NOT EXISTS "numberOfChildren"        INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "directoryRole"           TEXT DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS "pvEmail"                 TEXT DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS "pvBlog"                  TEXT DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS "pvOfficePhone"           TEXT DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS "pvMobilePhone"           TEXT DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS "pvHousePhone"            TEXT DEFAULT 'Not Accessible',
  ADD COLUMN IF NOT EXISTS "pvAddress"               TEXT DEFAULT 'Not Accessible',
  ADD COLUMN IF NOT EXISTS "pvEmergency"             TEXT DEFAULT 'Manager',
  ADD COLUMN IF NOT EXISTS "pvBirthday"              TEXT DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS "pvFamilyBirthday"        TEXT DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS "pvAnniversary"           TEXT DEFAULT 'Employee',
  ADD COLUMN IF NOT EXISTS "remark"                  TEXT;
